# Generated by Django 5.0.6 on 2024-06-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gonggu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='end_time',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_photo',
            new_name='productImg',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_name',
            new_name='productName',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='user',
            new_name='sellerId',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='start_time',
            new_name='startDate',
        ),
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.CharField(default='http://example.com', max_length=500),
        ),
    ]
