# Generated by Django 5.0.6 on 2024-06-23 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gonggu', '0002_rename_end_time_item_enddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sellerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='gonggu.user'),
        ),
    ]
